// <auto-generated />
using JC_ViaBrasil.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JC_ViaBrasil.Migrations
{
    [DbContext(typeof(TabelaFipeDbContext))]
    [Migration("20230822044231_AlteraTamanoCampos")]
    partial class AlteraTamanoCampos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JC_ViaBrasil.Models.TabelaFipe", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("anoModelo")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "anoModelo");

                    b.Property<string>("codigoFipe")
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasAnnotation("Relational:JsonPropertyName", "codigoFipe");

                    b.Property<string>("combustivel")
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasAnnotation("Relational:JsonPropertyName", "combustivel");

                    b.Property<string>("dataConsulta")
                        .HasMaxLength(150)
                        .HasColumnType("varchar")
                        .HasAnnotation("Relational:JsonPropertyName", "dataConsulta");

                    b.Property<string>("marca")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasAnnotation("Relational:JsonPropertyName", "marca");

                    b.Property<string>("mesReferencia")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasAnnotation("Relational:JsonPropertyName", "mesReferencia");

                    b.Property<string>("modelo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasAnnotation("Relational:JsonPropertyName", "modelo");

                    b.Property<string>("placaVeiculo")
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasAnnotation("Relational:JsonPropertyName", "placaVeiculo");

                    b.Property<string>("siglaCombustivel")
                        .HasMaxLength(1)
                        .HasColumnType("varchar")
                        .HasAnnotation("Relational:JsonPropertyName", "siglaCombustivel");

                    b.Property<int>("tipoVeiculo")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "tipoVeiculo");

                    b.Property<string>("valor")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasAnnotation("Relational:JsonPropertyName", "valor");

                    b.HasKey("id");

                    b.ToTable("TabelaFipe");
                });
#pragma warning restore 612, 618
        }
    }
}
